package util;

import util.DHUtil;

import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

// This is used to store the session key generated by the key agreement . This allows same client to come in again and execute a new key agreement.


public class SessionKeyCache {



    Map<String, DHUtil> cache = new ConcurrentHashMap<>();

    public void put(String sessionId , DHUtil util)
    {
        cache.put(sessionId,util);
    }


    // one time use only

    public DHUtil use(String sessionId)
    {
        return cache.remove(sessionId);
    }

    @Override
    public String toString() {
        return "SessionKeyCache{" +
                "cache=" + cache +
                '}';
    }
}
